[tools]
rojo = "rojo-rbx/rojo@7.4.4"
wally = "upliftgames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.3.2"
luau-lsp = "JohnnyMorganz/luau-lsp@1.34.0"
selene = "kampfkarren/selene@0.27.1"
stylua = "JohnnyMorganz/StyLua@0.20.0"
