[package]
name = "bdidk235/react-tooltip"
description = "A react version of bdidk235/tooltip, that is a basic text tooltip that that follows your mouse."
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml"]

[dependencies]
# jsdotlua React (Roact17)
React = "jsdotlua/react@^17"
ReactRoblox = "jsdotlua/react-roblox@^17"

Sift = "csqrl/sift@^0.0"
