[package]
name = "bdidk235/tooltip"
description = "A basic text tooltip that that follows your mouse."
version = "1.0.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["src", "src/**", "default.project.json", "wally.toml"]

